import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import Header from "../components/layout/Header";
import Container from "../components/layout/Container";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["600"], // SemiBold
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="font-sans">
        <Header />
        <main>
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
